redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  config:
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

# global:
#   image:
#     repository: "localhost:5001/argoproj/argocd"

# dex:
#   image:
#     repository: "localhost:5001/dexidp/dex"

# redis:
#   image:
#     repository: "localhost:5001/docker/library/redis"

configs:
  secret:
    argocdServerAdminPassword: $2y$10$W2rHjrwJy4zRjpV3pWuYdOGJo4gqH0dvizYu2of3TZm.hfw4kfmhy
