apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout
  namespace: 
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: 2.25.0
    chart: argo-rollouts

  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: argo-rollouts

  syncPolicy:
    automated:
      selfHeal: true
      prune: true