apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: 1.17.1
      chart: gateway

    - repoURL: "https://github.com/da1rren/argocd-istio.git"
      helm:
        valueFiles:
        - $values/environments/local/istio-gateway/values.yaml
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: istio-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
