apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: 
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: 1.17.1
    chart: base
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
