apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"

spec:
  project: default

  destination:
    server: '{{ .Values.spec.destination.server }}'
    namespace: istio-system
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

  sources:
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: 1.17.1
      chart: istiod
      helm:
        valueFiles:
        - $values/environments/local/istio-istiod/values.yaml

    - repoURL: 'https://github.com/da1rren/argocd-istio.git'
      targetRevision: HEAD
      ref: values
