apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook
  labels:
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"