apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
source:
  repoURL: "https://istio-release.storage.googleapis.com/charts"
  targetRevision: 1.17.1
  chart: istiod
destination:
  server: "https://kubernetes.default.svc"
  namespace: istio-system
